In [4]:
import pandas as pd


rev = pd.read_csv("revenue.csv", index_col="Date")

rev.head()

        New York  Los Angeles  Miami
Date
1/1/16       985          122    499
1/2/16       738          788    534
1/3/16        14           20    933
1/4/16       730          904    885
1/5/16       114           71    253

In [5]:
s  = pd.Series([1,2,3])
s.sum()

6

In [6]:
rev.sum()

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [8]:
rev.sum(axis=0)
rev.sum(axis="index")

New York       5475
Los Angeles    5134
Miami          5641
dtype: int64

In [10]:
rev.sum(axis=1)
rev.sum(axis="columns")

Date
1/1/16     1606
1/2/16     2060
1/3/16      967
1/4/16     2519
1/5/16      438
1/6/16     1935
1/7/16     1234
1/8/16     2313
1/9/16     2623
1/10/16     555
dtype: int64

In [14]:
nba = pd.read_csv("nba.csv")
nba.head(11)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
5,Amir Johnson,Boston Celtics,90.0,PF,29.0,6-9,240.0,NaN,12000000.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0

In [17]:
nba.Name.head()

type(nba.Name)

pandas.core.series.Series

In [21]:
nba["Name"]

nba["Team"].head()

0    Boston Celtics
1    Boston Celtics
2    Boston Celtics
3    Boston Celtics
4    Boston Celtics
Name: Team, dtype: object

In [24]:
nba[["Team","Name","Weight"]]

Select = ["Team","Name","Weight"]

nba[Select]

                       Team                     Name  Weight
0            Boston Celtics            Avery Bradley   180.0
1            Boston Celtics              Jae Crowder   235.0
2            Boston Celtics             John Holland   205.0
3            Boston Celtics              R.J. Hunter   185.0
4            Boston Celtics            Jonas Jerebko   231.0
5            Boston Celtics             Amir Johnson   240.0
6            Boston Celtics            Jordan Mickey   235.0
7            Boston Celtics             Kelly Olynyk   238.0
8            Boston Celtics             Terry Rozier   190.0
9            Boston Celtics             Marcus Smart   220.0
10           Boston Celtics          Jared Sullinger   260.0
11           Boston Celtics            Isaiah Thomas   185.0
12           Boston Celtics              Evan Turner   220.0
13           Boston Celtics              James Young   215.0
14           Boston Celtics             Tyler Zeller   253.0
15            Brooklyn Nets         Bojan Bogdanovic   216.0
16            Brooklyn Nets             Markel Brown   190.0
17            Brooklyn Nets          Wayne Ellington   200.0
18            Brooklyn Nets  Rondae Hollis-Jefferson   220.0
19            Brooklyn Nets             Jarrett Jack   200.0
20            Brooklyn Nets           Sergey Karasev   208.0
21            Brooklyn Nets          Sean Kilpatrick   219.0
22            Brooklyn Nets             Shane Larkin   175.0
23            Brooklyn Nets              Brook Lopez   275.0
24            Brooklyn Nets         Chris McCullough   200.0
25            Brooklyn Nets              Willie Reed   220.0
26            Brooklyn Nets          Thomas Robinson   237.0
27            Brooklyn Nets               Henry Sims   248.0
28            Brooklyn Nets             Donald Sloan   205.0
29            Brooklyn Nets           Thaddeus Young   221.0
..                      ...                      ...     ...
428  Portland Trail Blazers          Al-Farouq Aminu   215.0
429  Portland Trail Blazers          Pat Connaughton   206.0
430  Portland Trail Blazers             Allen Crabbe   210.0
431  Portland Trail Blazers                 Ed Davis   240.0
432  Portland Trail Blazers         Maurice Harkless   215.0
433  Portland Trail Blazers         Gerald Henderson   215.0
434  Portland Trail Blazers              Chris Kaman   265.0
435  Portland Trail Blazers           Meyers Leonard   245.0
436  Portland Trail Blazers           Damian Lillard   195.0
437  Portland Trail Blazers            C.J. McCollum   200.0
438  Portland Trail Blazers             Luis Montero   185.0
439  Portland Trail Blazers            Mason Plumlee   235.0
440  Portland Trail Blazers            Brian Roberts   173.0
441  Portland Trail Blazers              Noah Vonleh   240.0
442               Utah Jazz            Trevor Booker   228.0
443               Utah Jazz               Trey Burke   191.0
444               Utah Jazz               Alec Burks   214.0
445               Utah Jazz               Dante Exum   190.0
446               Utah Jazz           Derrick Favors   265.0
447               Utah Jazz              Rudy Gobert   245.0
448               Utah Jazz           Gordon Hayward   226.0
449               Utah Jazz              Rodney Hood   206.0
450               Utah Jazz               Joe Ingles   226.0
451               Utah Jazz            Chris Johnson   206.0
452               Utah Jazz               Trey Lyles   234.0
453               Utah Jazz             Shelvin Mack   203.0
454               Utah Jazz                Raul Neto   179.0
455               Utah Jazz             Tibor Pleiss   256.0
456               Utah Jazz              Jeff Withey   231.0
457                     NaN                      NaN     NaN

[458 rows x 3 columns]